# Generated by Django 4.2.1

from django.db import migrations, models
import django.contrib.gis.db.models.fields

class Migration(migrations.Migration):
    # Initial migration for creating the Point model
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),  # Point name field
                ('description', models.TextField(blank=True)),  # Optional description
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),  # Geographic location
            ],
        ),
    ]
